defaults:
  - hydra: default
  - _self_

experiment: "my_dataset"
save_format: "png"

num_train: 20_000  # Number of episodes in the 'train' split.
num_val: 2_000
num_test: 2_000

num_workers: 8

env:
  _target_: envs.make_env
  suite: mof  # Should be "mof", "gym", or "dmcontrol".
  name: ReachRed_0to4Distractors_Dense-v1
  image_size: [ 64, 64 ]
  max_episode_steps: 25
  action_repeat: 2

