defaults:
  - autoencoder: savi  # Select the autoencoder architecture to train (cnn, savi)
  - callbacks: autoencoder
  - hydra: default
  - logger: wandb
  - trainer: gradient_clipping
  - _self_

checkpoint: ""
experiment: "finger_spin_color_easy"
seed: 42

dataset:
  _target_: datasets.image.load_image_dataset
  path: ../experiments/generate_dmcgb_dataset/finger_spin_color_easy
  data_dir: 2025-07-18_18-09-38
  num_workers: 8
  batch_size: 64
  sequence_length: 8

model:
  _target_: train_autoencoder.AutoencoderModule
  autoencoder: ${..autoencoder}

  optimizer:
    _target_: torch.optim.Adam
    _partial_: True
    lr: 0.0001

  scheduler:
    scheduler:
      _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
      _partial_: True
      warmup_epochs: 10  # Number of warmup epochs.
      max_epochs: ${....trainer.max_epochs}
    extras:
      interval: "epoch"
